# Generated by Django 4.2 on 2023-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_social_aboutimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
