# Generated by Django 4.2 on 2023-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='min_read',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
